### ISSUE TITLE
lung medical image registration

### ISSUE THREAD

**Issue by lxy51** [uncbiag/ICON#68]
Thank you for the successful code. Can you share your preprocessing code for lung data?

**Comment by HastingsGreer** [comment]
Sure! https://github.com/uncbiag/ICON/blob/f23a6983011d1b135b435c21ea2ee9a3cf14871c/src/icon_registration/pretrained_models/lung_ct.py#L76

**Comment by lxy51** [comment]
> 当然！
> 
> https://github.com/uncbiag/ICON/blob/f23a6983011d1b135b435c21ea2ee9a3cf14871c/src/icon_registration/pretrained_models/lung_ct.py#L76

Thank you very much for your help
